apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: rust-service-ingress
  annotations:
   # Group Definition 
   # All ingress objects w/ this group will be pooled together versus creating an alb per ingress
   # This is the most desirable configuration
    alb.ingress.kubernetes.io/group.name: lowsandbox.com 
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Health check settings
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    # -- Creates Loabalancers of type "Classic"; this is no longer desriable
    # service.beta.kubernetes.io/aws-load-balancer-type: "external"
    # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"

spec:
  ingressClassName: alb
  rules:
  - host: "rust-service.lowsandbox.com"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: rust-service
              port:
                number: 80
